# Generated by Django 4.2.1 on 2023-05-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_description',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
