# Generated by Django 4.2.1 on 2023-05-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_category_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default='', upload_to='jobs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=15),
        ),
    ]
