# Generated by Django 4.2.1 on 2023-05-08 15:49

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_image_alter_job_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_title',
        ),
        migrations.AddField(
            model_name='job',
            name='job_time',
            field=models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time')], default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(upload_to=job.models.upload_img),
        ),
    ]
