# Generated by Django 4.2.1 on 2023-05-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_remove_job_job_title_job_job_time_alter_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
