# Generated by Django 4.2.1 on 2023-05-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_rename_job_description_job_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Benefits',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='Qualifications',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='Responsibility',
            field=models.TextField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=15),
        ),
    ]
