# Generated by Django 4.2.1 on 2023-05-10 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_alter_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='filled_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='form',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='apply_job', to='job.job'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time')], max_length=15),
        ),
    ]
